# numpy.ndarray 中行和列的基本操作

In [1]:
import numpy as np

a = np.arange(12)       # 构建一个从整数0到11的numpy.ndarray对象，然后查看该对象的内容
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [2]:
type(a)  

numpy.ndarray

In [3]:
a.shape # 查看数组的维度：一维数组，12个元素

(12,)

In [4]:
a.shape = 3, 4  # 改变数组的维度

In [5]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
a[2]    # 获取索引位2上的行

array([ 8,  9, 10, 11])

In [7]:
a[2, 1]  # 获取索引为2，1的元素

9

In [8]:
a[:, 1] # 获取索引为1上的列

array([1, 5, 9])

In [9]:
a.transpose()   # 转置数组（行列交换）， 创建一个新数组

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [10]:
a.shape

(3, 4)

In [11]:
a.shape = 4

ValueError: cannot reshape array of size 12 into shape (4,)

In [14]:
a.shape = 4, 3
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
a.transpose() 

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [16]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])